services:
  postgres:
    image: postgres:17
    container_name: postgres-335159
    environment:
      POSTGRES_DB: verifier_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    ports:
      - "33510:5432"
    volumes:
      - postgres_data_335159:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d verifier_service"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_335159:
