server:
  port: "${VERIFIER_SERVICE_PORT}"

spring:
  main:
    banner-mode: "off"
  datasource:
    own:
      username: ${CONTAINER.USERNAME}
      password: ${CONTAINER.PASSWORD}
      url: ${CONTAINER.URL}
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: "update"
    properties:
      jakarta:
        persistence:
          validation:
            mode: "auto"
  mvc:
    pathmatch:
      matching-strategy: "ant_path_matcher"
